apiVersion: v1
kind: ConfigMap
metadata:
  name: ctdl-xtra-config
  namespace: ctdl-xtra
data:
  CLIENT_PATH: /app/public
  EXTRACTION_FILES_PATH: /app/storage
  FRONTEND_URL: https://ctdl-xtra.credentialengineregistry.org
  INSPECT_WORKERS: "1"
  PORT: "3000"
  REDIS_URL: redis://redis:6379
  VITE_API_URL: https://ctdl-xtra.credentialengineregistry.org
