apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ctdl-xtra-secrets
  namespace: ctdl-xtra
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-manager
    kind: ClusterSecretStore
  target:
    name: ctdl-xtra-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: ctdl-xtra
