version: '3.8'

services:
  
  ctdl-xtra:
    build: .
    container_name: ctdl-xtra
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://xtra:xtra@postgres:5432/cdtlxtra
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"
    volumes:
      - .:/app
  ctdl-xtra-worker:
    build: 
      context: .
      dockerfile: worker.Dockerfile
    container_name: ctdl-xtra-worker
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgres://xtra:xtra@postgres:5432/xtra
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/app
 
  postgres:
    image: postgres:latest
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: xtra
      POSTGRES_PASSWORD: xtra
      POSTGRES_DB: xtra
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:
