apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ctdl-xtra-api
  namespace: ctdl-xtra
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ctdl-xtra
      app.kubernetes.io/component: api
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: ctdl-xtra-worker
  namespace: ctdl-xtra
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ctdl-xtra
      app.kubernetes.io/component: worker
