controller:
  # Single system node (us-east-1a): one replica.
  replicaCount: 1
  nodeSelector:
    nodepool: system
  service:
    externalTrafficPolicy: Local
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: nlb
      service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
