installCRDs: true

serviceAccount:
  name: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::996810415034:role/ctdl-xtra-staging-external-secrets-irsa-role

env:
  AWS_REGION: us-east-1
  AWS_DEFAULT_REGION: us-east-1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
